### PR TITLE
Fix compilation with Qt 5.14

### LINKED ISSUE #52: Fails to compile with Qt 5.14
Starting with Qt 5.14 qtmir doesn't compile anymore:
```
/home/pmos/build/src/qtmir-f1a612ce524c57f689b68c6f3b57fdfe8d169560/src/modules/Unity/Application/mirsurfaceitem.cpp: In member function 'virtual QSGNode* qtmir::MirSurfaceItem::updatePaintNode(QSGNode*, QQuickItem::UpdatePaintNodeData*)':
/home/pmos/build/src/qtmir-f1a612ce524c57f689b68c6f3b57fdfe8d169560/src/modules/Unity/Application/mirsurfaceitem.cpp:237:20: error: no matching function for call to 'QSGDefaultInternalImageNode::QSGDefaultInternalImageNode()'
  237 |         node = new QSGDefaultInternalImageNode;
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/pmos/build/src/qtmir-f1a612ce524c57f689b68c6f3b57fdfe8d169560/src/modules/Unity/Application/mirsurfaceitem.cpp:35:
/usr/include/QtQuick/5.14.1/QtQuick/private/qsgdefaultinternalimagenode_p.h:78:5: note: candidate: 'QSGDefaultInternalImageNode::QSGDefaultInternalImageNode(QSGDefaultRenderContext*)'
   78 |     QSGDefaultInternalImageNode(QSGDefaultRenderContext *rc);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/QtQuick/5.14.1/QtQuick/private/qsgdefaultinternalimagenode_p.h:78:5: note:   candidate expects 1 argument, 0 provided
make[2]: *** [src/modules/Unity/Application/CMakeFiles/unityapplicationplugin.dir/build.make:194: src/modules/Unity/Application/CMakeFiles/unityapplicationplugin.dir/mirsurfaceitem.cpp.o] Error 1

```
See qtdeclarative commit: https://github.com/qt/qtdeclarative/commit/341ab7708049b1a3f559b76f16393e688951a938

Fixing this seems to be non-trivial, at least I haven't managed to do it yet.

### PR DESCRIPTION
**Pull request by z3ntu**
Fixes #52

**Please note that I have no idea if this works in runtime.** The tests of qtmir still succeed but I doubt that they test this part of the code.

The changes are a mashup of what can be found in https://github.com/qt/qtdeclarative/commit/341ab7708049b1a3f559b76f16393e688951a938

### CODE REVIEW

**Review by mariogrip — APPROVED** [review]
LGTM :+1: 

seems to work fine on arch
