### ISSUE TITLE
Fails to compile with Qt 5.14

### ISSUE THREAD

**Issue by z3ntu** [ubports/qtmir#52]
Starting with Qt 5.14 qtmir doesn't compile anymore:
```
/home/pmos/build/src/qtmir-f1a612ce524c57f689b68c6f3b57fdfe8d169560/src/modules/Unity/Application/mirsurfaceitem.cpp: In member function 'virtual QSGNode* qtmir::MirSurfaceItem::updatePaintNode(QSGNode*, QQuickItem::UpdatePaintNodeData*)':
/home/pmos/build/src/qtmir-f1a612ce524c57f689b68c6f3b57fdfe8d169560/src/modules/Unity/Application/mirsurfaceitem.cpp:237:20: error: no matching function for call to 'QSGDefaultInternalImageNode::QSGDefaultInternalImageNode()'
  237 |         node = new QSGDefaultInternalImageNode;
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/pmos/build/src/qtmir-f1a612ce524c57f689b68c6f3b57fdfe8d169560/src/modules/Unity/Application/mirsurfaceitem.cpp:35:
/usr/include/QtQuick/5.14.1/QtQuick/private/qsgdefaultinternalimagenode_p.h:78:5: note: candidate: 'QSGDefaultInternalImageNode::QSGDefaultInternalImageNode(QSGDefaultRenderContext*)'
   78 |     QSGDefaultInternalImageNode(QSGDefaultRenderContext *rc);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/QtQuick/5.14.1/QtQuick/private/qsgdefaultinternalimagenode_p.h:78:5: note:   candidate expects 1 argument, 0 provided
make[2]: *** [src/modules/Unity/Application/CMakeFiles/unityapplicationplugin.dir/build.make:194: src/modules/Unity/Application/CMakeFiles/unityapplicationplugin.dir/mirsurfaceitem.cpp.o] Error 1

```
See qtdeclarative commit: https://github.com/qt/qtdeclarative/commit/341ab7708049b1a3f559b76f16393e688951a938

Fixing this seems to be non-trivial, at least I haven't managed to do it yet.

**Comment by mariogrip** [comment]
I wish i could get my PMos env to work so i could help more effectively out

**Comment by z3ntu** [comment]
Still this weird error you posted some time ago?
